
## Assessment 1:

### Assessment 1.1

**Focus**: Basic R, RMarkdown and `tidyverse` data wrangling
1. Setup your Assessment 1 project:

- Create a new Github repo in your Github account.
- Set up this project in your RStudio as shown in class.
- create a RMarkdown document and save it in this project using assessment1.rmd
- Delete parts that you do not need in the RMarkdown template generated by default and copy the tasks below there. You need to leave the `meta data` section and initial R chunk.
- The title of your document should be Assessment 1.1
- The Author is your name and student id
- The date is the date you created he document

You will need to answer each task using the text/graph narration and include R chunks to show how you get them.

2. Create the heading of the first level and call it RMarkdown editing

3. Write 2-3 sentences about RMarkdown (you can google this information or use resources recommended in class - no need to reference)

4. In the above use bold and italics for editing.

5. Review the suggested documentation on how to insert links in the .rmd file and include an in-text link to https://rmarkdown.rstudio.com/lesson-8.html

6. Insert an R chunk and create a variable with this dataset
https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv

The name of the variable should be `fastfood`

7. Display the first 10 rows of the dataset. Use Help to see how you can do this with `head()` function.

8. Display the observations that has more than 1000 calories

9. Save observations with more than 40 in total_fat and more than 80 in total_carb in a new variable called `dont_eat_this`

10. Using the initial dataset variable, display observations from restaurant Mcdonalds

- Save your .rmd file 

- Do a commit in Git tab

- Push in the same tab


### Assessment 1.2

**Focus**: `tidyverse` data wrangling (adv) and `ggplot2`

1. Setup your Assessment 1 project:

- Use the same  Github repo in your Github account you used for Assessment 1.1.
- Open  this project in your RStudio as shown in class. You saved this project on your local computer, so please reopen it from there
- Create a RMarkdown document and save it in this project using assessment1.2.rmd
- Delete parts that you do not need in the RMarkdown template generated by default and copy the tasks below there. You need to leave the `meta data` section and initial R chunk.
- The title of your document should be Assessment 1.2
- The Author is your name and student id
- The date is the date you created he document

You will need to answer each task using the text/graph narration and include R chunks to show how you get them.

2. Create the heading of the first level and call it Data wrangling

3. Insert an R chunk and create a variable with this dataset
https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv

The name of the variable should be `fastfood`

Display the types of variables in the dataset using `skimr` package

4. Show the number of observations for each restaurant.

5. Calculate and display the average number of calories for each restaurant.

6. Add a variable to the dataset, which calculates the average calories per type of restaurant and call it `average_calories` 

7. Display the data vis of total fat per each type of restaurant. Write a narration (2-3 sentences) why you believe this type of data viz presents such information best. **

8. Display the count of observations per each type of restaurant

9. Add a variable to the dataset, which calculates the maximum total fat per type of restaurant and call it `max_total_fat` 

10. Use observations for Mcdonalds to plot sugar variable against protein with `geom_point()` 

- Save your .rmd file 

- Do a commit in Git tab

- Push in the same tab



### Assessment 1.3

**Focus**: ggplot2, factors, strings, dates  

1. Setup your Assessment 1 project:

- Use the same  Github repo in your Github account you used for Assessment 1.1.
- Open  this project in your RStudio as shown in class. You saved this project on your local computer, so please reopen it from there
- Create a RMarkdown document and save it in this project using assessment1.3.rmd
- Delete parts that you do not need in the RMarkdown template generated by default and copy the tasks below there. You need to leave the `meta data` section and initial R chunk.
- The title of your document should be Assessment 1.3
- The Author is your name and student id
- The date is the date you created he document

- Create the heading of the first level and call it Data viz and wrangling

- Insert an R chunk and create a variable with this dataset
https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv

The name of the variable should be `fastfood`

2. Using `skimr` package provide a list of variables which types needs to be changed 
Use R function to identify the types of variables. What changes do you need to do to correctly record the types of variables? 
Does all variables have sufficient range (=variability) to be included? Which variable can be removed?

Write 2-3 sentences justifying your view on the above.

3. Identify variable(s) which should be factors and transform their type into a factor variable.

4. Replace NA in the dataset with 0 across all variables

5. Create two new variables:

Read about `cut_number()` function using Help and add a new variable to the dataset `calories_type`. Use `calories` variable for `cut_number()` function to split it into 3 categories `n=3`, add labels `labels=c("low", "med", "high")` and make the dataset ordered. 

Do not forget to save the updated dataset. 

6. Create a dataviz that shows the distribution of `calories_type` in food items for each type of restaurant. Think carefully about the choice of data viz. Use facets, coordinates and theme layers to make your data viz visually appealing and meaningful. Use factors related data viz functions.

7. The second variable should show the percentage of `trans_fat` in `total_fat`. Add the variable to the dataset and call it `trans_fat_percent`. Do not forget to save the updated dataset. 

8. Create a dataviz that shows the distribution of `trans_fat` in food items for each type of restaurant. Think carefully about the choice of data viz. Use facets, coordinates and theme layers to make your data viz visually appealing and meaningful.

9. Calculate the average (mean)  `total_fat` for each type of restaurant. No need to save it as a variable.

11. And create a dataviz that allow to compare different restaurants on this variable (`total_fat`). You can present it on one dataviz (= no facets). 

Think carefully about the choice of data viz. Use coordinates and theme layers to make your data viz visually appealing and meaningful. 


