---
title: "Assessment 1"
author: "Maria Prokofieva"
date: "18/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(skimr)
```

#RMarkdown editing


*vvv*

**bbb**

```{r}
fastfood<-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")

fastfood%>%head(n=10)

knitr::kable(fastfood[1:10,1:5])


```

8. filter()

9. dont_eat_this<-filter()
arrange(desc(X1))


Using the initial dataset variable, use `case_when()` to create a new variable `heavy_food` which is equal to "heavy" when total calories are greater than 500, "low" when total calories are less than 250 and "average" for all other cases. Count the number of observations in each created category.

```{r}
fastfood%>%
  mutate(
    heavy_food=case_when(
      calories>500~"heavy",
      calories<250~"low",
      T~"average"
    )
         )%>%
  count(heavy_food, sort=TRUE)
```


```{r}
skim(fastfood)
```

12. count (sort=)

distinct()

13.group_by(restaurant)
summarise(avr_cal=mean(calories))

14.mutate(
v1=mean(),
v2=max(),
v3=min()
)

